### ISSUE TITLE
Updating question/answer queries sometimes sends HTML to the database

### ISSUE THREAD

**Issue by masonmcelvain** [calpoly-csai/nimbus-validator-app#20]
While testing the update_phrase flask route, we discovered that it is possible to unintentionally add `<span>...</span>` HTML to the question and answer fields of a query. This seems to happen when the text between two blue tokens is deleted, and the tokens are allowed to touch one another, and then text is replaced between the tokens.

For example:
Trying to change the answer:
`[COURSE] is about [COURSE..desc]`
to:
`[COURSE] covers [COURSE..desc]`
could actually change the answer in the database to:
`[COURSE]<span style={background: rgb(255,255,255)}> covers </span>[COURSE..desc]`

**Comment by Waidhoferj** [comment]
Good catch, before you send it to the server, just check for the carets and remove the tags.
