### ISSUE TITLE
Unintentionally deleting non-breaking spaces before tokens before pushing to database

### ISSUE THREAD

**Issue by masonmcelvain** [calpoly-csai/nimbus-validator-app#36]
Non breaking spaces that precede token names are deleted before being pushed to the database. This needs to be fixed so we aren't unintentionally trashing data in the database.

#### Example:
`for&nbsp;[CLUB] => for[CLUB]`

**Comment by Waidhoferj** [comment]
Would this be fixed by our latest in progress PR #35? If not, I'd recommend looking at the `regex` variable in the update logic. Will look into this.

**Comment by masonmcelvain** [comment]
Yes @Waidhoferj I believe #35 will fix this issue. Regardless, it may be worth our time to look into that `regex` variable a little further :)
